# Generated by Django 4.1.5 on 2023-01-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('contact', '0002_alter_formfield_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactPage',
            new_name='FormPage',
        ),
    ]
