# Generated by Django 4.1.5 on 2023-01-06 13:23

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_rtfbody_homepage_rtf_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='schedule_block',
            field=wagtail.fields.StreamField([('sch_time', wagtail.blocks.CharBlock()), ('sch_body', wagtail.blocks.CharBlock()), ('sch_img', wagtail.images.blocks.ImageChooserBlock()), ('sch_leader', wagtail.blocks.CharBlock())], blank=True, use_json_field=None),
        ),
    ]
