# Generated by Django 4.1.5 on 2023-01-06 21:59

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_homepage_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='location',
            field=wagtail.fields.StreamField([('adress', wagtail.blocks.CharBlock(max_length=150, required=True)), ('telegram', wagtail.blocks.CharBlock(max_length=60, required=True)), ('email', wagtail.blocks.CharBlock(max_length=60, required=True))], blank=True, null=True, use_json_field=True),
        ),
    ]
