# Generated by Django 4.1.5 on 2023-01-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_homepage_about_img_homepage_about_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='about_title_body',
            new_name='about_body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_title',
        ),
    ]
