# Generated by Django 4.1.5 on 2023-01-06 06:53

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_rtfbody_alter_homepage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='str_body',
            field=wagtail.fields.StreamField([('rich_block', wagtail.blocks.RichTextBlock()), ('img_block', wagtail.blocks.ChoiceBlock(choices=[]))], blank=True, use_json_field=None),
        ),
    ]
