# Generated by Django 4.1.5 on 2023-01-06 07:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_str_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='rtfbody',
            new_name='rtf_body',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='str_body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('rich_block', wagtail.blocks.RichTextBlock()), ('img_block', wagtail.images.blocks.ImageChooserBlock())], blank=True, use_json_field=None),
        ),
    ]
