# Generated by Django 4.1.5 on 2023-01-06 17:09

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_content_homepage_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='schedule',
            field=wagtail.fields.StreamField([('cards', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('time', wagtail.blocks.CharBlock(max_length=40, required=True)), ('title', wagtail.blocks.CharBlock(max_length=200, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('leader', wagtail.blocks.TextBlock(max_length=100, required=True))])))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
