# Generated by Django 4.1.5 on 2023-01-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_homepage_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='date_event',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
