# Generated by Django 4.1.5 on 2023-01-08 18:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0019_rename_about_title_body_homepage_about_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='location',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_body',
            field=models.TextField(blank=True, null=True, verbose_name='Заметка "О нас"'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Изображение в блоке "О нас"'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='book_body',
            field=models.TextField(blank=True, null=True, verbose_name='Вторая заметка в блоке "О нас"'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='book_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Второй заголовок в блоке "О нас"'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='date_event',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата события (в шапке)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='guests',
            field=wagtail.fields.StreamField([('guests', wagtail.blocks.StructBlock([('guests', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('name', wagtail.blocks.TextBlock(max_length=100, required=True)), ('prof', wagtail.blocks.TextBlock(max_length=100, required=True))])))]))], blank=True, null=True, use_json_field=True, verbose_name='Карточки гостей (в блоке "Гости")'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='schedule',
            field=wagtail.fields.StreamField([('cards', wagtail.blocks.StructBlock([('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('time', wagtail.blocks.CharBlock(max_length=40, required=True)), ('title', wagtail.blocks.CharBlock(max_length=200, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('leader', wagtail.blocks.TextBlock(max_length=100, required=True))])))]))], blank=True, null=True, use_json_field=True, verbose_name='Карточки-Пункты "Расписания"'),
        ),
    ]
